### PR TITLE
Support rerun C++ API 0.18

### PR DESCRIPTION
**Pull request by jeongseok-meta**
Differential Revision: D61489537

### CODE REVIEW

**Comment by jeongseok-meta** [comment]
This is pending due to https://github.com/conda-forge/rerun-sdk-feedstock/pull/45

**Comment by traversaro** [comment]
> This is pending due to [conda-forge/rerun-sdk-feedstock#45](https://github.com/conda-forge/rerun-sdk-feedstock/pull/45)

I guess it may be also blocked by https://github.com/conda-forge/librerun-sdk-feedstock/pull/13 .

**Comment by jeongseok-meta** [comment]
Also blocked by https://github.com/conda-forge/librerun-sdk-feedstock/pull/16

**Comment by jeongseok-meta** [comment]
Closing in favor of https://github.com/facebookincubator/momentum/pull/65

**Pull request closed without merging**
